name: analysis_server_crash
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  # cv: '0.2.9+2'
  cv: '>=0.2.10-1'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
